version: "3.7"
services:
  main:
    image: iso:main
    build: .
    ports:
      - "8022:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  # custom:
  #   build:
  #     context: ./custom
  #   ports:
  #     - "8122:22"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock