FROM iso:main
# FROM docker.pkg.github.com/<your-github-user>/iso/main:0.1

ARG USER

# Add custom setup and configuration here

# Install Golang
# RUN wget https://dl.google.com/go/go1.14.3.linux-amd64.tar.gz
# RUN sudo tar -C /usr/local -xzf go1.14.3.linux-amd64.tar.gz
# RUN sed -i '/export PATH=/s/.*/export PATH=$HOME\/go\/bin:\/usr\/local\/go\/bin:$PATH/' ~/.zshrc

USER root